### ISSUE TITLE
Doesn't compile on ArchLinux kernel 5.0.0-arch1-1

### ISSUE THREAD

**Issue by githubixx** [zebulon2/rtl8812au#23]
Hi! Arch updated the kernel to 5.0.0-arch1-1 today. But that causes the driver to not build anymore. Here is the [make.log](https://github.com/zebulon2/rtl8812au/files/2932690/make.log).

**Comment by zebulon2** [comment]
I have added a patch for 5.0. Can you please try again?

**Comment by githubixx** [comment]
I've switched to a different AUR and I don't want to change that now. But I cloned the repo, executed `dkms-install.sh` and commented out `dkms install -m ...` (https://github.com/zebulon2/rtl8812au/blob/v5.1.5/dkms-install.sh#L23) to not override my current module. I can confirm that at least everything compiles now. So I would assume that the module also works. :+1:
